# Generated by Django 3.0 on 2020-02-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='keyword',
            field=models.CharField(max_length=1024),
        ),
    ]
